### ISSUE TITLE
Code smell: A lot of mutations

### ISSUE THREAD

**Issue by zsoerenm** [JuliaGNSS/GNSSDecoder.jl#3]
There are a lot of mutations in this implementation. This makes it difficult to reason about.
Moreover, Testing this module is hard (see all the deep copies in test). A change somewhere might cause an error or a testing failure at some complete other place.

I dream of an implementation, where every function has no side effects (does not mutate any of the input parameters). This should eliminate the difficulties described above.
The state of the decoder could be save in a variable, which is then again passed to the `decode` function.
```julia
decoding_state = Decoder(prn)
for i in 1:iterations
    track_res = track(signal, track_state , sampling_freq)
    track_state = get_state(track_res)
    decoding_state = decode(decoding_state, get_bits(track_res), get_num_bits(track_res))
end
```
BitIntegers might be of help here. It provides longer integers than UInt64. So you could create an integer with a length of 312 by the following:
```
julia> BitIntegers.@define_integers 312
julia> UInt312(1)
julia> Int312(1)
```
It provides necessary shifts, etc.
This should be a lot more performant, although compared to tracking, it does not make a real difference.

**Comment by dominformant** [comment]
We could even think about (manually) buffering in 10 `UInt32`, where each word directly contains the 2 previous bits required for Parity checking. This would also remove the need to split the buffer in the individual words.

**Comment by zsoerenm** [comment]
Sounds great, but how would you handle a new incoming bit?
I guess you can avoid to shift the bit from the right, can you? Simply put it into the right place?
The parity bits would then be part of two 32bit-"words"? So one 32bit "word" would contain its own parity bits and the ones of the next 32bit "word"?

**Comment by dominformant** [comment]
Each incoming bit would lead to a shift of all words by one place and then adding bit 30 (or 31) from one word to bit 0 from the next higher word. The parity bits are then part of two words, that's right, but actually intended. However, I'm not sure, whether this leads to more overhead than using a `UInt320` and splitting this in the individual words (including the parity) before decoding.

**Comment by dominformant** [comment]
Actually, as the next preamble is also required, using a `UInt310` should be preferable

**Comment by zsoerenm** [comment]
It must be multiples of 8. This is why I suggested `UInt312`.

**Comment by dominformant** [comment]
Okay, I did not know that. Would than maybe `UInt320` be even preferable, as this could be mapped to 5 `UInt64`?

**Comment by zsoerenm** [comment]
Do we need 5 `UInt64`? I think performance-wise is there no difference between `UInt312` and `UInt320`

**Comment by dominformant** [comment]
Actually no, 310 Bit are sufficient, I just thought it could be a performance improvement, but I must admit I don't know how it is implemented in `BitIntegers.jl`.

**Comment by zsoerenm** [comment]
This is fixed with https://github.com/JuliaGNSS/GNSSDecoder.jl/pull/9
