### ISSUE TITLE
Prepare Multi-GNSS capabilities

### ISSUE THREAD

**Issue by dominformant** [JuliaGNSS/GNSSDecoder.jl#5]
With the current naming of the data structures, the implementation of additional GNSSs is quite difficult. In order to prepare the usage of other GNSS, I would suggest restructuring the data structures.

https://github.com/JuliaGNSS/GNSSDecoder.jl/blob/8550134798166cda2da51ac8da14d64a65465f2b/src/gpsl1_structs.jl#L59-L98

My Idea is to have something like that for the decoded data:
```
abstract type EphemerisGNSS;
typedef struct EphemerisGPSL1 < EphemerisGNSS
    ...
end
typedef struct EphemerisGalileoE1 < EphemerisGNSS
    ...
end
typedef struct EphemerisGPSL5 < EphemerisGNSS
    ...
end
```

And in the same way the decoder states:
```
abstract type DeoderState;
typedef struct DeoderStateGPSL1 < DeoderState
    ...
end
typedef struct DeoderStateGalileoE1 < DeoderState
    ...
end
typedef struct DeoderStateGPSL5 < DeoderState
    ...
end
```

**Comment by zsoerenm** [comment]
This is fixed with https://github.com/JuliaGNSS/GNSSDecoder.jl/pull/9
